### ISSUE TITLE
Combining items doesn't make an outcome 

### ISSUE THREAD

**Issue by jamesreii** [codetaylor/pyrotech#252] opened 2019-12-02 19:18 UTC
#### Issue Description

*[Currently, combining items in a worktable doesn't create an outcome unless using a crafting table or GUI crafting grid]*

#### What Happens

*[When combining resources in a worktable, particularly potions [Combined Potions Mod] and liners with armour [Armour Underwear Mod], once hammered, the items disappear and doesn't seem to make the combined item]*

#### What You Expect to Happen

*[I would expect that the item would appear in my inventory but it just disappears]*

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 2847
* CraftTweaker: N/A
* Dropt: 1.16.1
* Pyrotech: 1.4.13
* Athenaeum: 1.17.4

**Comment by katubug** [comment] 2019-12-27 00:08
I popped by to report something different and came across this issue, and decided to test, since I am also using some of those mods. I can confirm that this occurs when applying the liners from ArmorUnderwear. I note that it does not affect all recipes from the mod - I was able to craft the actual liners, it was just when trying to apply the liners to armor that the recipe completes but does not output a finished item of any kind.

Minecraft: 1.12.2
Forge: 2847
Armor Underwear: 1.0.0
CarrotsLib: 1.0.0b1
Pyrotech: 1.4.16
Athenaeum: 1.17.4
Dropt: 1.16.1

Here's an excerpt from the latest.log, in which I attempted to apply one of each type of liner to its respective Diamond armor counterpart.

```
[18:04:25] [Server thread/INFO]: <Katubug> this is a placeholder
[18:04:25] [Client thread/INFO]: [CHAT] <Katubug> this is a placeholder
[18:04:30] [Client thread/INFO]: [CHAT] Set player temperature to 12
[18:04:33] [Server thread/WARN]: Potentially Dangerous alternative prefix `armorunder` for name `lined_helmet_1layer_cool`, expected `pyrotech`. This could be a intended override, but in most cases indicates a broken mod.
[18:04:47] [Server thread/WARN]: Potentially Dangerous alternative prefix `armorunder` for name `optional/antifreeze_lined_leggings`, expected `pyrotech`. This could be a intended override, but in most cases indicates a broken mod.
[18:04:53] [Server thread/WARN]: Potentially Dangerous alternative prefix `armorunder` for name `optional/obsidian_lined_boots`, expected `pyrotech`. This could be a intended override, but in most cases indicates a broken mod.
[18:04:58] [Server thread/INFO]: <Katubug> and done
[18:04:58] [Client thread/INFO]: [CHAT] <Katubug> and done
```

Let me know if you'd like me to get you any other information on this!

**Comment by katubug** [comment] 2019-12-27 19:50
I had some more free time, so here's a full latest.log: https://pastebin.com/YsDSnzFG

I created an isolated instance with the following mods/versions:
- **Forge**: 2847
- **Armor Underwear Mod**: 1.0.0
- **Athenaeum**: 1.17.4
- **Carrot Library**: 1.0.0.b1
- Dropt 1.16.1
- JEI: 4.15.0.293
- Patchouli: 1.0-20
- **Pyrotech**: 1.4.17

Loaded up the game with no configs generated, created a new creative world, and exited the game. Loaded back up and entered the same world. Gave myself both worktables, a diamond hammer, and 3 matching pieces of diamond armor and Armor Underwear liners (one cooling, one warming, one auto-regulating). Changed mode to survival (previous tests were in creative), and did 1 recipe on the wooden Workbench and 2 on the Stone Workbench. All 3 tests consumed the items and did not provide an output.

I've never seen the "potentially dangerous prefix" error outside of initialization, so I'm guessing that's related, but I'm not sure how. In any case, hope this helps!

**Comment by codetaylor** [comment] 2019-12-29 19:08
I was able to reproduce this using the vanilla dye + leather armor recipe.

**Comment by codetaylor** [comment] 2019-12-29 19:24
![image](https://user-images.githubusercontent.com/1240716/71561570-42277b00-2a2d-11ea-92ce-99207d6c4b25.png)

It should be fixed in the next patch version. Waila doesn't respect the item's NBT data when rendering the item, but afaik that's a Waila issue.

**Comment by katubug** [comment] 2019-12-29 21:02
Update, using the build you linked in discord - 

latest.log: https://pastebin.com/BhpNBKvB

Tests were conducted on the wooden Workbench.

- Iron Helmet, Helmet Warm Liner x3: First 2 attempts worked, third consumed the items.
- Diamond Chestplate, Ozzy Chestplate Liner x2: First attempt worked, second consumed the items. However, it is only supposed to apply once. Attempts to apply it a second time in the vanilla crafting table refuse to output.
- Leather Pants, Leggings Warm Liner x2, Leggings Cool Liner x1: First two applications worked, third consumed the items.
- Golden Boots, Boots Cool Liner x1, Boots Warm Liner x1: First attempt worked, second consumed the items.

Testing a second time, with the ArmorUnder liner limit increased from 3 to 8.

- Diamond Chestplate, Cool Liner, in Worktable: First 3 attempts worked, 4th attempt consumed the items.
- Iron Chestplate, Warm Liner, in Crafting Bench: First 3 attempts worked, 4th attempt doesn't offer an output.

I did a third test with the ArmorUnder config increased from 8 to 99, and it still only allows 3 applications, so that part is just an issue on their end. But in terms of this bug, it seems it now allows the items to be "worked" on the workbench, even if there isn't a valid recipe output.

**Closed** 2019-12-30 01:22 UTC
Labels: bug, complete, reproduced
