### ISSUE TITLE
Problem with Torch position

### ISSUE THREAD

**Issue by LokyLive** [codetaylor/pyrotech#147] opened 2019-08-08 14:41 UTC
#### What Happens

When i pass on a torch placed on the ground, I go down from a block in the ground at the torch's place. Like a torch placed on a slab XD

affected items : Stone torch (lit and unlit) / Fiber torch (lit and unlit)

#### Crash Log

no crash ! 

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 2838
* CraftTweaker: 4.1.19
* Dropt: 1.15.1
* Pyrotech:1.12.2 -1.3.2
* Athenaeum: 1.17.3

**Comment by codetaylor** [comment] 2019-08-08 17:09
I'm not able to reproduced this.

I've tried walking through an unlit fiber torch repeatedly like this:

![2019-08-08_10-07-14](https://user-images.githubusercontent.com/1240716/62722949-66be8000-b9c4-11e9-8412-d708c00df311.gif)

**Comment by LokyLive** [comment] 2019-08-08 18:49
i will try to find what could cause this ,i'll be back later with answer ;p

**Comment by nicolhaq** [comment] 2019-08-08 18:50
I think that this is a weird interaction with this mod 
https://www.curseforge.com/minecraft/mc-mods/ido

**Comment by LokyLive** [comment] 2019-08-08 19:00
yep i've just found the issue and it came from ido
https://www.curseforge.com/minecraft/mc-mods/ido

**Comment by codetaylor** [comment] 2019-08-08 19:06
Yeah, it looks like the mod is forcing a player to sneak when you walk on or through some blocks: https://github.com/Kaydax/Ido/issues/21

**Comment by codetaylor** [comment] 2019-08-14 20:44
I'm closing this because it is not Pyrotech's domain.

**Closed by codetaylor** 2019-08-14 20:44 UTC
Labels: mod interaction, wontfix
